import { Inter } from 'next/font/google'
import './globals.css'

import Header from '@/components/Header'
import Footer from '@/components/Footer'
import ThemeProvider from '@/components/Theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Kementrian Perindustrian',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute='class' defaulttheme='light'>
          <Header />
          <div className='mt-20 mb-6 px-4 lg:px-10 3xl:px-40'>
            {children}
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
